## Lab Introduction
Enhance! You've probably seen a movie or TV show where the super spy agents use some unbelievable technique to enhance a pixelated image, or to recover some lossy data. In this lab, you're going to do something similar—this time your objective is to use linear regression to recover or 'fill out' a completely deleted portion of an audio file!

To complete this lab, you will be using The FSDD, Free-Spoken-Digits-Dataset, an audio dataset put together by Zohar Jackson once he noticed there weren't very many cleaned up audio (no dead-space, roughly same length, same bitrate, same samples-per-second rate, etc) audio libraries ready for machine learning.

In [1]:
import numpy as np
import pandas as pd

from sklearn.utils.validation import check_random_state
import scipy.io.wavfile as wavfile

### About Audio

Samples are Observations. Each audio file will is a single sample in our dataset.

Find more information about [Audio Samples here](https://en.wikipedia.org/wiki/Sampling_(signal_processing)).

Each .wav file is actually just a bunch of numeric samples, "sampled" from the analog signal. Sampling is a type of discretization. When we mention 'samples', we mean observations. When we mention 'audio samples', we mean the actually "features" of the audio file.

The goal of this lab is to use multi-target, linear regression to generate by extrapolation, the missing portion of the test audio file.

Each one audio_sample features will be the output of an equation, which is a function of the provided portion of the audio_samples:

    missing_samples = f(provided_samples)

You can experiment with how much of the audio you want to chop off and have the computer generate using the Provided_Portion parameter.

Play with this. This is how much of the audio file will be provided, in percent. The remaining percent of the file will be generated via linear extrapolation.

In [2]:
Provided_Portion = 0.25

## 1. Data Preparation

You have to download the dataset (audio files) from the website: https://github.com/Jakobovski/free-spoken-digit-dataset

Start by creating a regular Python List called `zero`:

In [3]:
# .. your code here ..
zero = []

Loop through the dataset and load up all 50 of the `0_jackson*.wav` files using the `wavfile.read()` method: https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.io.wavfile.read.html Be careful! `.read()` returns a tuple and you're only interested in the audio data, and not sample_rate at this point. Inside your for loop, simply append the loaded audio data into your Python list `zero`:

In [4]:
# .. your code here ..
file_url = r'C:\Users\tocba\Documents\GitHub\Python\Funix_DataScience\DSP303\free-spoken-digit-dataset-master\recordings'
for i in range(50):
    zero.append(wavfile.read(file_url+'/0_jackson_'+str(i)+'.wav')[1])
zero[:5]

[array([-369, -431, -475, ...,  301,  324,  304], dtype=int16),
 array([-311,  -91, -140, ...,  378,  357,  333], dtype=int16),
 array([-361, -226, -238, ..., -286, -311, -343], dtype=int16),
 array([ 323,  338,  357, ..., -246, -280, -301], dtype=int16),
 array([-302, -312, -103, ..., -338, -333, -348], dtype=int16)]

Just for a second, convert zero into a DataFrame. When you do so, set the `dtype` to `np.int16`, since the input audio files are 16 bits per sample. If you don't know how to do this, read up on the docs here: http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html

Since these audio clips are unfortunately not length-normalized, we're going to have to just hard chop them to all be the same length. Since Pandas would have inserted NANs at any spot to make zero a  perfectly rectangular [n_observed_samples, n_audio_samples] array, do a `dropna` on the Y axis here. Then, convert one back into an NDArray using `yourarrayname.values`:

In [5]:
# .. your code here ..
df = pd.DataFrame(zero, dtype='int16')
df.head()

0     1     2     3     4     5     6     7     8     9     ...  6263  \
0  -369  -431  -475  -543  -571  -557  -528  -455  -394  -305  ...   NaN   
1  -311   -91  -140  -182  -271   -68  -235  -359  -129  -198  ...   NaN   
2  -361  -226  -238  -478  -425  -395  -663  -879  -726  -997  ...   NaN   
3   323   338   357   388   381   393   391   378   348   313  ...   NaN   
4  -302  -312  -103  -305  -145  -339    12  -433  -141  -189  ...   NaN   

   6264  6265  6266  6267  6268  6269  6270  6271  6272  
0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
1   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
2   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
3   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
4   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  

[5 rows x 6273 columns]

In [6]:
df.dropna(axis=1,inplace=True)
df.head()

0     1     2     3     4     5     6     7     8     9     ...  4077  \
0  -369  -431  -475  -543  -571  -557  -528  -455  -394  -305  ...  2475   
1  -311   -91  -140  -182  -271   -68  -235  -359  -129  -198  ...  -122   
2  -361  -226  -238  -478  -425  -395  -663  -879  -726  -997  ...  -141   
3   323   338   357   388   381   393   391   378   348   313  ...  1323   
4  -302  -312  -103  -305  -145  -339    12  -433  -141  -189  ...   189   

   4078  4079  4080  4081  4082  4083  4084  4085  4086  
0  2500  2331  1786  1057   358   158  -108  -402  -884  
1  -207  -266  -276  -316  -359  -396  -422  -462  -460  
2   -83     0    71   165   284   325   378   416   438  
3  1321  1211   827   292  -244  -779 -1241 -1369 -1229  
4   211   189   134   150   224   265   313   328   327  

[5 rows x 4087 columns]

In [7]:
zero = df.values

It's important to know how (many audio_samples samples) long the data is now.

`zero` is currently shaped like `[n_samples, n_audio_samples]`, so get the `n_audio_samples` count and store it in a variable called `n_audio_samples`:

In [8]:
# .. your code here ..
n_audio_samples = zero.shape[1]

In [9]:
n_audio_samples

4087

## 2. Training the Model

Create your linear regression model here and store it in a variable called `model`. Don't actually train or do anything else with it yet:

In [10]:
# .. your code here ..
from sklearn import linear_model
model = linear_model.LinearRegression()

There are 50 takes of each clip. You want to pull out just one of them, randomly, and that one will NOT be used in the training of your model. In other words, the one file we'll be testing / scoring on will be an unseen sample, independent to the rest of your training set:

In [11]:
# Leave this line alone until you've submitted your lab:
rng = check_random_state(7)

random_idx = rng.randint(zero.shape[0])
test  = zero[random_idx]
train = np.delete(zero, [random_idx], axis=0)

Print out the shape of `train`, and the shape of `test`.

`train` will be shaped: `[n_samples, n_audio_samples]`, where `n_audio_samples` are the 'features' of the audio file 

`test` will be shaped `[n_audio_features]`, since it is a single sample (audio file, e.g. observation).

In [12]:
# .. your code here ..
print(train.shape)
print(test.shape)

(49, 4087)
(4087,)


The test data will have two parts, `X_test` and `y_test`.

`X_test` is going to be the first portion of the test audio file, which we will be providing the computer as input. 

`y_test`, the "label" if you will, is going to be the remaining portion of the audio file. Like such, the computer will use linear regression to derive the missing portion of the sound file based off of the training data its received!

Let's save the original `test` clip, the one you're about to delete half of, to the current directory so that you can compare it to the 'patched' clip once you've generated it. You should have already got the `sample_rate` when you were loading up the .wav files:

In [13]:
sample_rate = wavfile.read(file_url+'/0_jackson_0.wav')[0]

In [14]:
wavfile.write('Original Test Clip.wav', sample_rate, test)

Prepare the TEST data by creating a slice called `X_test`. It should have `Provided_Portion` * `n_audio_samples` audio sample features, taken from your test audio file, currently stored in variable `test`. In other words, grab the FIRST `Provided_Portion` * `n_audio_samples` audio features from `test` and store it in `X_test`. This should be accomplished using indexing:

In [20]:
int(Provided_Portion * n_audio_samples)

1021

In [52]:
# .. your code here ..
X_test = test[:int(Provided_Portion * n_audio_samples)]

If the first `Provided_Portion` * `n_audio_samples` features were stored in `X_test`, then we need to also grab the _remaining_ audio features and store them in `y_test`. With the remaining features stored in there, we will be able to R^2 "score" how well our algorithm did in completing the sound file.

In [57]:
X_test.shape

(1, 1021)

In [35]:
# .. your code here ..
y_test = test[int(Provided_Portion * n_audio_samples):]

Duplicate the same process for `X_train`, `y_train`. The only differences being:

1. Your will be getting your audio data from `train` instead of from `test`
2. Remember the shape of `train` that you printed out earlier? You want to do this slicing but for ALL samples (observations). For each observation, you want to slice the first `Provided_Portion` * `n_audio_samples` audio features into `X_train`, and the remaining go into `y_train`. All of this should be doable using regular indexing in two lines of code:

In [36]:
# .. your code here ..
X_train = train[:,:int(Provided_Portion * n_audio_samples)]
y_train = train[:,int(Provided_Portion * n_audio_samples):] 

SciKit-Learn gets 'angry' if you don't supply your training data in the form of a 2D dataframe shaped like `[n_samples, n_features]`.

So if you only have one SAMPLE, such as is our case with `X_test`, and `y_test`, then by calling `.reshape(1, -1)`, you can turn `[n_features]` into `[1, n_features]` in order to appease SciKit-Learn.

On the other hand, if you only have one FEATURE, you can alternatively call `.reshape(-1, 1)` on your data to turn `[n_samples]` into `[n_samples, 1]`.

Reshape X_test and y_test as [1, n_features]:

In [58]:
X_train.shape

(49, 1021)

In [54]:
# .. your code here ..
X_test = X_test.reshape(1,-1)
y_test = y_test.reshape(1,-1)

Fit your model using your training data and label:

In [56]:
X_test.shape

(1, 1021)

In [38]:
# .. your code here ..
model.fit(X_train, y_train)

LinearRegression()

## 3. Model Evaluation

Use your model to predict the `label` of `X_test`. Store the resulting prediction in a variable called `y_test_prediction`:

In [39]:
# .. your code here ..
y_test_prediction = model.predict(X_test)

SciKit-Learn will use float64 to generate your predictions so let's take those values back to int16, which is what our .wav files expect:

In [40]:
y_test_prediction = y_test_prediction.astype(dtype=np.int16)

Score how well your prediction would do for some good laughs, by passing in your test data and test label `y_test`:

In [60]:
y_test.reshape(-1,1)

array([[-3306],
       [-1833],
       [ -893],
       ...,
       [ 1433],
       [ 1616],
       [ 1427]], dtype=int16)

In [61]:
y_test_prediction.reshape(-1,1)

array([[-3697],
       [-2611],
       [ -950],
       ...,
       [  365],
       [  -91],
       [ -482]], dtype=int16)

In [62]:
# .. your code here ..
from sklearn.metrics import r2_score
score = r2_score(y_test.reshape(-1,1),y_test_prediction.reshape(-1,1))

In [63]:
print("Extrapolation R^2 Score: ", score)

Extrapolation R^2 Score:  0.9999772826862826


Let's take the first `Provided_Portion` portion of the test clip, the part you fed into your linear regression model. Then, stitch that together with the 'abomination' the predictor model generated for you and then save the completed audio clip:

In [64]:
completed_clip = np.hstack((X_test, y_test_prediction))
wavfile.write('Extrapolated Clip.wav', sample_rate, completed_clip[0])